### ISSUE TITLE
Alternative approach

### ISSUE THREAD

**Issue by jdsn** [mvidner/donotedit#2]
When reading about this concept I realised that it requires to touch every config file change that any $yastmodule is doing. As this is not exclusively done via SCR I think it is hard to implement such a warning message in all modules.

What about a different approach:
YaST (control center or some part in y2base) could check if chef is installed (and/or running) and then show this warning message. This is just to remind the admin, that this machine is somehow under chefs control.

**Comment by tgoettlicher** [comment]
I think that approach also makes sence. One remark: Please do NOT put that check to Control Center because desktops might directly launch YaST modules.

**Comment by mvidner** [comment]
Hmm, it is a bit coarse but very simple and probably good enough. Thanks, Daniel.

For the record, the original request suggested an approach that lies in between: a Chef cookbook would set a flag in some dedicated file that would trigger warnings with yast-module granularity.

**Comment by jdsn** [comment]
AFAIK this is resolved. Closing.
